import express from "express";
import pool from "../db.js";

const router = express.Router();

// ─── GENERATE CERTIFICATE (Hospital only) ─────────────────────────────────────
router.post("/generate", async (req, res) => {
  const hospital_id = req.user.id;
  const { donor_id, request_id } = req.body;

  if (!donor_id) {
    return res.status(400).json({ message: "donor_id is required" });
  }

  try {
    // Verify donor actually accepted an SOS from this hospital
    const donationCheck = await pool.query(
      `SELECT rr.donor_id, d.name AS donor_name, d.blood_group,
              h.name AS hospital_name
       FROM request_responses rr
       JOIN emergency_requests er ON er.request_id = rr.request_id
       JOIN donors d ON d.donor_id = rr.donor_id
       JOIN hospitals h ON h.hospital_id = er.hospital_id
       WHERE rr.donor_id = $1
         AND er.hospital_id = $2
         AND rr.response_status = 'ACCEPTED'
       LIMIT 1`,
      [donor_id, hospital_id]
    );

    if (donationCheck.rows.length === 0) {
      return res.status(403).json({
        message: "This donor has not accepted any SOS from your hospital",
      });
    }

    const { donor_name, blood_group, hospital_name } = donationCheck.rows[0];

    // Return existing certificate if already generated for same donor+hospital+request
    const existing = await pool.query(
      `SELECT * FROM donation_certificates
       WHERE donor_id = $1 AND hospital_id = $2
       ${request_id ? "AND request_id = $3" : ""}
       LIMIT 1`,
      request_id ? [donor_id, hospital_id, request_id] : [donor_id, hospital_id]
    );

    if (existing.rows.length > 0) {
      return res.json({ message: "Certificate already exists", certificate: existing.rows[0] });
    }

    // Generate new certificate — UUID token auto-generated by DB
    const result = await pool.query(
      `INSERT INTO donation_certificates
        (donor_id, hospital_id, request_id, blood_group, donor_name, hospital_name)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING *`,
      [donor_id, hospital_id, request_id || null, blood_group, donor_name, hospital_name]
    );

    res.json({ message: "Certificate generated successfully", certificate: result.rows[0] });

  } catch (err) {
    console.error("Certificate generate error:", err);
    res.status(500).json({ error: err.message });
  }
});

// ─── GET DONOR'S OWN CERTIFICATES ─────────────────────────────────────────────
router.get("/my", async (req, res) => {
  const donor_id = req.user.id;
  try {
    const result = await pool.query(
      `SELECT c.*, h.address AS hospital_address, h.locality AS hospital_locality
       FROM donation_certificates c
       JOIN hospitals h ON h.hospital_id = c.hospital_id
       WHERE c.donor_id = $1
       ORDER BY c.issued_at DESC`,
      [donor_id]
    );
    res.json(result.rows);
  } catch (err) {
    console.error("Certificates fetch error:", err);
    res.status(500).json({ error: err.message });
  }
});

// ─── GET HOSPITAL'S RECENTLY DONATED DONORS ───────────────────────────────────
router.get("/recent-donors", async (req, res) => {
  const hospital_id = req.user.id;
  try {
    const result = await pool.query(
      `SELECT DISTINCT ON (rr.donor_id)
         rr.donor_id,
         d.name         AS donor_name,
         d.blood_group,
         d.phone,
         rr.response_time,
         rr.request_id,
         (
           SELECT certificate_token FROM donation_certificates
           WHERE donor_id = rr.donor_id AND hospital_id = $1
           LIMIT 1
         ) AS certificate_token
       FROM request_responses rr
       JOIN emergency_requests er ON er.request_id = rr.request_id
       JOIN donors d ON d.donor_id = rr.donor_id
       WHERE er.hospital_id = $1
         AND rr.response_status = 'ACCEPTED'
       ORDER BY rr.donor_id, rr.response_time DESC
       LIMIT 20`,
      [hospital_id]
    );
    res.json(result.rows);
  } catch (err) {
    console.error("Recent donors error:", err);
    res.status(500).json({ error: err.message });
  }
});

// ─── VERIFY CERTIFICATE (Public — no token needed) ────────────────────────────
router.get("/verify/:token", async (req, res) => {
  const { token } = req.params;
  try {
    const result = await pool.query(
      `SELECT c.*, h.address AS hospital_address, h.locality AS hospital_locality
       FROM donation_certificates c
       JOIN hospitals h ON h.hospital_id = c.hospital_id
       WHERE c.certificate_token = $1`,
      [token]
    );
    if (result.rows.length === 0) {
      return res.status(404).json({ message: "Certificate not found or invalid token" });
    }
    res.json({ valid: true, certificate: result.rows[0] });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

export default router;